# .github/workflows/deploy.yml

name: Build and Deploy RAG API

# This workflow runs on every push to the 'main' branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # Use a standard Linux server for the job

    steps:
      # Step 1: Check out your code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Step 3: Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          platform: linux/amd64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/rag-api:latest

      # Step 4: Authenticate to Google Cloud
      - name: Authenticate to Google Cloud
        uses: "google-github-actions/auth@v2"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      # Step 5: Deploy to Google Cloud Run
      - name: Deploy to Cloud Run
        uses: "google-github-actions/deploy-cloudrun@v2"
        with:
          service: rag-api-service # The name of your Cloud Run service
          region: us-central1 # IMPORTANT: Change this to your service's region
          image: docker.io/${{ secrets.DOCKERHUB_USERNAME }}/rag-api:latest
          flags: "--memory=8Gi --cpu=2 --min-instances=0 --max-instances=5"
